apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-anz
  region: ap-southeast-1
nodeGroups:
   - name: nodegroup
     desiredCapacity: 1
     instanceType: t3.small
     ssh:
        publicKeyName: test_key